### ISSUE TITLE
epic: provide one AWS account to each consultant

### ISSUE THREAD

**Issue by bernard357** [reply-fr/sustainable-personal-accounts#1]
Epic steps:
- [x] from Control Tower, create an OU Released Accounts within OU Sandbox
- [x] provision on AWS account for b.paques@reply.com -- see below
- [x] provision on AWS account for b.gauchon@reply.com -- see below
- [x] provision on AWS account for s.loubeyres@reply.com -- see below
- [x] provision on AWS account for y.flourac@reply.com -- see below
- [x] provision on AWS account for y.mnani@reply.com -- see below

Steps for the provisioning of an AWS account:
- go to SSO > Users and ensure that target e-mail account exists and has at least one registered MFA device
- collect input information: e-mail address, first name and last name
- go to Service Catalog > Products > AWS Control Tower Account Factory
- click on button Launch product
- in field Provisioned product name, append automatic label with consultant id, e.g. 'AWS_Control_Tower_Account_Factory-11261013-s.loubeyres'
- paste email address in fields: AccountEmail, AccountName, SSOUserEmail
- select OU Released Accounts for field ManagedOrganizationalUnit
- type first name in field SSOUserFirstName
- type last name in field SSOUserLastName
- go to Control Tower > Accounts
- wait until account has been created and successfully enrolled
- go to Organizations and navigate to the new account in its OU
- add a tag with key 'account:holder' and e-mail address as value
- go to AWS SSO > AWS Accounts
- select new AWS account and click on Assign users ; on following page, select the user with same e-mail address ; on following page, select AWSAdministratorAccess and click on button Finish
- go to AWS SSO > Users
- click on user account for the target e-mail and review groups ; apply changes
- update table on Teams with the list of AWS accounts used by team members
