### ISSUE TITLE
epic: purge IAM users from AWS sandbox account 792281704736

### ISSUE THREAD

**Issue by bernard357** [reply-fr/sustainable-personal-accounts#2]
Purpose of this epic is to ensure that no Storm reply consultant is using IAM user credential to access the sandbox account, once everybody has received a personal AWS account for himself.

- [x] disable IAM user @ sandbox account for n.joillot@reply.com -- see below
- [x] disable IAM user @ sandbox account for y.mnani@reply.com -- see below
- [x] disable IAM user @ sandbox account for y.flourac@reply.com -- see below
- [x] disable IAM user @ sandbox account for s.loubeyres@reply.com -- see below
- [x] disable IAM user @ sandbox account for b.gauchon@reply.com -- see below

For each IAM user found on sandbox account 792281704736:
- disable console access
- disable CLI access with AK and SK
